### ISSUE TITLE
問apt-get某些套件的必要性

### ISSUE THREAD

**Issue by lmly9193** [Leezj9671/SecDevices_docker#3]
Leezj9671 你好

* apt-utils
* net-tools

安裝這兩個套件的用意是什麼呢? acunetix需要使用嗎? 望解惑

**Comment by Leezj9671** [comment]
实际上没有必要，是将之前的Dockerfile文件复制黏贴顺手而为……😂

**Comment by Leezj9671** [comment]
`apt-utils` 在使用 `apt` 的时候需要使用，否则会出现警告（但不影响实际安装），迫于强迫症，我就安装上了😂
`net-tools` 是用来 debug 网络的，可以无视
